swagger: "2.0"
info:
  description: "Circly Google Cloud Endpoints API."
  title: "Circly Endpoints"
  version: "1.0.0"
host: "circly-174919.appspot.com"

x-google-endpoints:
- name: "circly-174919.appspot.com"
  allowCors: "true"
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "key"
    in: "query"
  firebase:
    authorizationUrl: ""
    flow: "implicit"
    type: "oauth2"
    x-google-issuer: "https://securetoken.google.com/circly-174919"
    x-google-jwks_uri: "https://www.googleapis.com/service_accounts/v1/metadata/x509/securetoken@system.gserviceaccount.com"
    x-google-audiences: "circly-174919"
security:
    - api_key: []
      firebase: []

basePath: /api/v1
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /collection:
    get:
      description: "Returns all the collections available"
      operationId: "GetAllCollections"
      parameters: []
      responses:
        200:
          description: "Array of collections"
          schema:
            type: array
            items:
              $ref: "#/definitions/model.Collection"
      x-swagger-router-controller: "GetAllCollections"
    post:
      description: "Add a new collection"
      operationId: "AddCollection"
      parameters:
        - in: body
          name: "collection"
          description: "The collection to be added"
          required: true
          schema:
            $ref: "#/definitions/model.Collection"
      responses:
        200:
          description: "New collection created"
          schema:
            $ref: "#/definitions/model.Collection"
      x-swagger-router-controller: "AddCollection"
definitions:
  model.Collection:
    title: Collection
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      description:
        type: string
      createdMicros:
        type: integer
        minimum: -9007199254740991
        maximum: 9007199254740991
      authorId:
        type: string
      subscriberId:
        type: array
        items:
          type: string
      itemId:
        type: array
        items:
          type: string
